#!/usr/bin/env python
import os.path
import sys
from optparse import OptionParser

# check if the pymol module is installed
try :
    import pymol
except :
    sys.exit( "error : This script needs 'pymol' module. Please install pymol before running." )


# OptionParser
def opt() :
    # set an explanation of this program
    usage  = "%prog [options] PDB_FILE"
    dscrpt = ( "Show the structure of the  PDB_FILE by CA backbone using PyMOL."
               "PyMOL needs to be installed." )
    parser = OptionParser( usage = usage, description = dscrpt )

    # set options

    # cartoon mode
    parser.add_option( "-c", "--cartoon", dest = "mode", default = "stick",
                       action = "store_const", const = "cartoon",
                       help = "Display in CA trace cartoon mode [ default : stick mode ]" )

    # Connect separate atoms or not
    parser.add_option( "-s", "--separate", default = False, action = "store_true",
                       help = "Do not connect discontinuous CA atoms. If not specified, "
                       "[ default : force connect distant CA atoms ]" )

    # parse arguments
    ( options, args ) = parser.parse_args()

    # check arguments
    if len( args ) != 1 :
        parser.error( "Incorrect number of arguments. "
                      "Just one PDB_FILE must be given. \n"
                      "\t\tTo show help message, use '-h or --help' option." )

    return [ options.mode, options.separate, args[0] ]


########################################## main ##############################################

# get options
[ mode, separate, file ] = opt()


# check if "file" exists
if not os.path.isfile( file ) :
    sys.exit( "error : \"" + file + "\" : no such file" )


# make CA model
pdbdat = ""
bonds  = []
skip   = True
last   = 0
resnum = 1

for line in open( file, 'r' ).readlines() :

    # if not ATOM line
    if not line[0:4] == 'ATOM':
        continue
    
    # check atom type
    if line[12:16] != " CA " :
        continue

    # add pdb line
    pdbdat += line[0:22] + ( '%4d' % resnum ) + line[26:]
    resnum += 1

    # add bonds
    bonds.append( ( str(resnum - 2) + "/CA", str(resnum - 1) + "/CA" ) )


# launch pymol
pymol_argv = [ 'pymol', '-q' ]

pymol.finish_launching()
pymol.cmd.read_pdbstr( pdbdat, os.path.basename( file ) ) 
pymol.cmd.hide( 'everything' )

if mode == "stick" :
    for bond in bonds :
        pymol.cmd.bond( bond[0], bond[1] )
else :
    pymol.cmd.set( "cartoon_trace", 1 )

pymol.cmd.show( mode )
pymol.cmd.spectrum()

